extraction:
  image_path: dataset/images
  features: 
  output_path: dataset/features
matching:
  pairs: dataset/gt/night.txt
  feature: 
  feature_path: dataset/features
  output_path: dataset/matches
  matcher: 
matching_loftr:
  pairs: dataset/gt/night.txt
  image_path: dataset/images
  matches: dataset/matches
  features: dataset/features