extraction:
  image_path: dataset/pitts250k/images/test
  features: superpoint_max
  output_path: dataset/pitts250k/bench/features
matching:
  pairs: dataset/pitts250k/retrieval_results/test/pairs_20.txt
  feature: superpoint_max
  feature_path: dataset/pitts250k/bench/features
  output_path: dataset/pitts250k/bench/matches
  matcher: superglue
matching_loftr:
  pairs: dataset/pitts250k/retrieval_results/test/pairs_20.txt
  image_path: dataset/pitts250k/images/test
  matches: dataset/pitts250k/bench/matches
  features: dataset/pitts250k/bench/features